### ISSUE TITLE
Kunden- und Lieferantennummern auskommentiert

### ISSUE THREAD

**Issue by mcgumbel** [equitania/v10-addons#1]
Hallo, vielen Dank für das tolle Plugin. Bei meiner myodoo V10 Installation wurden jedoch keine Kunden- und Lieferantennummern angezeigt. Die Ursache liegt in diesem View eq_res_partner_view.xml, weil dort die beiden Felder auskommentiert sind. Was ist denn der Grund dafür?

Nachdem der Abschnitt ab Zeile 116 einkomment ist, sind die Felder zu sehen.

**Comment by eqms** [comment]
Dies ist Teil unseres Finanzbuchhaltungspaketes ist, das wir nicht kostenlos zur Verfügung stellen.

**Comment by mcgumbel** [comment]
Ok, vielen Dank für die Info.
